### ISSUE TITLE
Add a parameter to the constructor to set URL

### ISSUE THREAD

**Issue by TheLLspectre** [bougarfaoui/ng2-socket-io#47]
Hey !!!

I try to find a way to put a parameter to the URL to have somethings like that:

> export class SocketRasp extends Socket
{
    ipAddress: String;
    constructor(ipAddress: String)
    {
        super({ url: 'http://'+ ipAddress + ':8080', options: {} });
    }
}

it's Possible ???

Because, i try and i have this error:

> Error: Can't resolve all parameters for SocketRasp: (?).
    at syntaxError (http://localhost:8100/build/vendor.js:80840:34)
    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:8100/build/vendor.js:94915:35)
    at CompileMetadataResolver._getTypeMetadata (http://localhost:8100/build/vendor.js:94783:26)
    at CompileMetadataResolver._getInjectableMetadata (http://localhost:8100/build/vendor.js:94769:21)
    at CompileMetadataResolver.getProviderMetadata (http://localhost:8100/build/vendor.js:95060:40)
    at http://localhost:8100/build/vendor.js:94989:49
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver._getProvidersMetadata (http://localhost:8100/build/vendor.js:94949:19)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8100/build/vendor.js:94604:50)
    at JitCompiler._loadModules (http://localhost:8100/build/vendor.js:105945:70)

**Comment by sadzfr** [comment]
Try changing the name of your Constructor's argument.

**Comment by TheLLspectre** [comment]
Nothing change ! I try a lot of different possibilities.

**Comment by sadzfr** [comment]
You are declaring two parameters with same name:
`ipAddress: String; /*<-- No need for this */ `
`constructor(ipAddress: String)`

**Comment by TheLLspectre** [comment]
I re try to fix this. So I delete this one, and have the same error.
I think this module isn't made to be reused with one constructor

EDIT: 
Ok i made a little mistake with my way to write "string" and not "String", and the error message is different

> Error: Uncaught (in promise): Error: No provider for String!
Error: No provider for String!
